# Generated by Django 4.1.3 on 2024-01-14 20:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_number', models.CharField(max_length=255, verbose_name='Номер заключения договора')),
                ('date_open', models.DateField(default=datetime.datetime(2024, 1, 14, 20, 30, 32, 523193, tzinfo=datetime.timezone.utc), verbose_name='Дата заключения договора')),
                ('date_close', models.DateField(default=datetime.datetime(2024, 1, 14, 20, 30, 32, 523362, tzinfo=datetime.timezone.utc), verbose_name='Дата закрытия договора')),
                ('note', models.CharField(max_length=255, verbose_name='Пояснения')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договора',
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Полное наименование банка')),
                ('name_short', models.CharField(max_length=255, verbose_name='Краткое наименование банка')),
                ('inn', models.CharField(max_length=255, verbose_name='ИНН')),
                ('bik', models.CharField(max_length=255, verbose_name='БИК')),
                ('cor_account', models.CharField(max_length=255, verbose_name='Номер корсчета')),
                ('number_account', models.CharField(max_length=255, verbose_name='Номер банковского счета')),
                ('city', models.CharField(max_length=255, verbose_name='Краткое наименование банка')),
            ],
            options={
                'verbose_name': 'Банк',
                'verbose_name_plural': 'Банки',
            },
        ),
        migrations.CreateModel(
            name='TypeAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_type', models.CharField(choices=[('BROKERAGE', 'Брокерский'), ('DEALER', 'Дилерский'), ('MANAGEMENT', 'Управления')], max_length=255, verbose_name='Тип аккаунта')),
            ],
            options={
                'verbose_name': 'Тип аккаунта',
                'verbose_name_plural': 'Типы аккаунтов',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=255, verbose_name='Номер инвестиционного счета')),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.typeaccount', verbose_name='Тип аккаунта')),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.agreement', verbose_name='Договор')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.bank', verbose_name='Банк')),
            ],
            options={
                'verbose_name': 'Аккаунт',
                'verbose_name_plural': 'Аккаунты',
            },
        ),
    ]
